const products = [
    {
        name: 'Apple iPhone 17 Pro',
        slug: 'apple-iphone-17-pro',
        brand: 'Apple',
        category: 'Smart Phones',
        description: 'The iPhone 17 Pro features titanium design, A19 Pro chip, and a pro camera system.',
        images: [
            'https://rukminim1.flixcart.com/image/1600/2140/xif0q/mobile/f/v/m/-original-imahft6chnx2vbuy.jpeg?q=60',
        ],
        variants: [
            {
                variantSlug: 'apple-iphone-17-pro-desert-titanium-256-gb-smart-phones',
                color: 'Desert Titanium',
                storage: '256GB',
                ram: '8GB',
                finish: 'Titanium',
                mrp: 134900,
                price: 127400,    
                images: [
                    'https://rukminim1.flixcart.com/image/1600/2140/xif0q/mobile/f/v/m/-original-imahft6chnx2vbuy.jpeg?q=60',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/m/n/c/-original-imahft6c3rbjysmg.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/t/1/p/-original-imahft6cag2fggja.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/b/o/v/-original-imahft6cvnadukgx.jpeg?q=90',
                ],
                stock: 20,
                isDefault: true,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 21234, totalAmount: 127404, cashback: 2000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 15098, totalAmount: 135882, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 11482, totalAmount: 137784, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'apple-iphone-17-pro-black-256-gb-smart-phones',
                color: 'Black Titanium',
                storage: '256GB',
                ram: '8GB',
                finish: 'Titanium',
                mrp: 134900,
                price: 127400,   
                images: [
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/f/r/h/-original-imahft6chdhxfwhj.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/u/1/y/-original-imahft6c4hzxwjws.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/e/a/x/-original-imahft6cggdjcqsv.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/v/g/v/-original-imahft6czhmgv3ec.jpeg?q=90',
                ],
                stock: 15,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 21234, totalAmount: 127404, cashback: 2000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 15098, totalAmount: 135882, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 11482, totalAmount: 137784, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'apple-iphone-17-pro-desert-titanium-512-gb-smart-phones',
                color: 'Desert Titanium',
                storage: '512GB',
                ram: '8GB',
                finish: 'Titanium',
                mrp: 154900,
                price: 147400,     
                images: [
                    'https://rukminim1.flixcart.com/image/1600/2140/xif0q/mobile/f/v/m/-original-imahft6chnx2vbuy.jpeg?q=60',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/m/n/c/-original-imahft6c3rbjysmg.jpeg?q=90',
                ],
                stock: 10,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 24567, totalAmount: 147402, cashback: 2000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 17474, totalAmount: 157266, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 13299, totalAmount: 159588, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'apple-iphone-17-pro-black-512-gb-smart-phones',
                color: 'Black Titanium',
                storage: '512GB',
                ram: '8GB',
                finish: 'Titanium',
                mrp: 154900,
                price: 147400,  
                images: [
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/f/r/h/-original-imahft6chdhxfwhj.jpeg?q=90',
                    'https://rukminim1.flixcart.com/image/3024/3024/xif0q/mobile/u/1/y/-original-imahft6c4hzxwjws.jpeg?q=90',
                ],
                stock: 8,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 24567, totalAmount: 147402, cashback: 2000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 17474, totalAmount: 157266, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 13299, totalAmount: 159588, cashback: 0, isRecommended: false },
                ],
            },
        ],
    },
    {
        name: 'Samsung Galaxy S24 Ultra',
        slug: 'samsung-galaxy-s24-ultra',
        brand: 'Samsung',
        category: 'Smart Phones',
        description: 'Galaxy S24 Ultra with built-in S Pen, 200MP camera, and Snapdragon 8 Gen 3 processor.',
        images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
        variants: [
            {
                variantSlug: 'samsung-galaxy-s24-ultra-titanium-black-256-gb-smart-phones',
                color: 'Titanium Black',
                storage: '256GB',
                ram: '12GB',
                finish: 'Matte',
                mrp: 134999,
                price: 124999,     
                images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
                stock: 18,
                isDefault: true,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 20834, totalAmount: 125004, cashback: 1500, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 14808, totalAmount: 133272, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 11249, totalAmount: 134988, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'samsung-galaxy-s24-ultra-titanium-gray-256-gb-smart-phones',
                color: 'Titanium Gray',
                storage: '256GB',
                ram: '12GB',
                finish: 'Matte',
                mrp: 134999,
                price: 124999,    
                images: ['https://images.unsplash.com/photo-1707153163032-411a13437258?w=800'],
                stock: 12,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 20834, totalAmount: 125004, cashback: 1500, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 14808, totalAmount: 133272, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 11249, totalAmount: 134988, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'samsung-galaxy-s24-ultra-titanium-black-512-gb-smart-phones',
                color: 'Titanium Black',
                storage: '512GB',
                ram: '12GB',
                finish: 'Matte',
                mrp: 154999,
                price: 144999,     
                images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800'],
                stock: 7,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 24167, totalAmount: 145002, cashback: 1500, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 17175, totalAmount: 154575, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 13041, totalAmount: 156492, cashback: 0, isRecommended: false },
                ],
            },
        ],
    },
    {
        name: 'Google Pixel 9 Pro',
        slug: 'google-pixel-9-pro',
        brand: 'Google',
        category: 'Smart Phones',
        description: 'Google Pixel 9 Pro with Google Tensor G4 chip, pro camera array, and 7 years of OS updates.',
        images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800'],
        variants: [
            {
                variantSlug: 'google-pixel-9-pro-obsidian-128-gb-smart-phones',
                color: 'Obsidian',
                storage: '128GB',
                ram: '16GB',
                finish: 'Polished',
                mrp: 109999,
                price: 99999,      
                images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800'],
                stock: 25,
                isDefault: true,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 16667, totalAmount: 100002, cashback: 1000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 11845, totalAmount: 106605, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 9004, totalAmount: 108048, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'google-pixel-9-pro-porcelain-128-gb-smart-phones',
                color: 'Porcelain',
                storage: '128GB',
                ram: '16GB',
                finish: 'Polished',
                mrp: 109999,
                price: 99999,     
                images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800'],
                stock: 20,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 16667, totalAmount: 100002, cashback: 1000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 11845, totalAmount: 106605, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 9004, totalAmount: 108048, cashback: 0, isRecommended: false },
                ],
            },
            {
                variantSlug: 'google-pixel-9-pro-obsidian-256-gb-smart-phones',
                color: 'Obsidian',
                storage: '256GB',
                ram: '16GB',
                finish: 'Polished',
                mrp: 119999,
                price: 109999,    
                images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800'],
                stock: 14,
                isDefault: false,
                emiPlans: [
                    { provider: 'HDFC Bank', tenureMonths: 6, interestRate: 0, monthlyAmount: 18334, totalAmount: 110004, cashback: 1000, cashbackNote: 'Instant cashback on HDFC Credit Card', isRecommended: true },
                    { provider: 'ICICI Bank', tenureMonths: 9, interestRate: 13, monthlyAmount: 13029, totalAmount: 117261, cashback: 0, isRecommended: false },
                    { provider: 'Bajaj Finance', tenureMonths: 12, interestRate: 15, monthlyAmount: 9903, totalAmount: 118836, cashback: 0, isRecommended: false },
                ],
            },
        ],
    },
]

